### ISSUE TITLE
Group capstone: set up your Kanban board

### ISSUE THREAD

**Issue by OybekKayumov** [OybekKayumov/javascript-capstone#21]
- In its description, paste a link to your GitHub project:

- [ ] [link to your GitHub project]( https://github.com/OybekKayumov/javascript-capstone/projects/1 )

  

- Add a note telling the reviewer how many people there are in your team:

- [ ] We are two students, but we will try complete tasks also for a third student
@fahdrahali  and @OybekKayumov

**Comment by Rustamxon7** [comment]
Hello TEAM, 

Good job so far!

### HIGHLIGHTS!

- No linters errors.💯

There are some issues that you still need to work on to go to the next project but you are almost there!


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Rustamxon7** [comment]
You made a great effort making this project!
However, some changes need to be done. All cards must be assigned (even for the group tasks) but as you can see in this image you guys have some tasks which are not been assigned. Kindly assign students for all tasks.
<img width="369" alt="Screen Shot 2022-04-11 at 4 52 01 PM" src="https://user-images.githubusercontent.com/69011963/162734756-24402043-d54c-475f-ac0e-a95b6271ea82.png">

**Comment by ShoiraTa** [comment]
## **STATUS: APPROVED  🟢 ** 
------
### Hi team, 

**Great work on making the changes requested by a previous reviewer 👏🏻** 

Your project is complete! . There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 

![5SW](https://user-images.githubusercontent.com/77038610/154919611-7d0675af-6364-45a3-92d6-eccd9b743ced.gif)

**Cheers and Happy coding! :clap: :clap: :clap:**

Feel free to leave any questions or comments in the PR thread by mentioning my Github username if something is not 100% clear.
***
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
